version: '3'
services:
  app:
    image: php:8.1-fpm
    container_name: laravel_app
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    depends_on:
      - mysql  # Зависимость от MySQL
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
